sudo: false
language: node_js
node_js:
- 4.2.3
before_deploy:
- npm run demo
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: O1xa08rqlaa66l193GEblNSBCbjlYhn8pVIf0zHXXW6VlIt0yuhkudfG0deTB9f+qXx9u/wWxwvcgZ+mmwUq54MQujgHV4gKMzj8gVtXF6ZEeIK0JYrbe5EQzg5ZLj1+ioopmoIhvL9gJZCiselgfs5laaD3HE6PKpNLrAnIYbZ+Luc6T0bJLqAZqcog4UMuwvq6QrQg1L7l3AljG+9EkwQXiiSXWZFnOPF+0ok4lWmXZrPE7m6vB90JaIxZW/ffkfpYZOUFhE8UGG/Cl4N8FnOsr5NqdHaXyTMl/NWQ13zIei+vsBsunaIAQNvVg77XSzbvLSpdwwVPcQdyw+qKv938JjWCzWBLIGMXZdJRCPZJdqZt+J47Tvy6q4uKEXW7k4/xHO5oafhUVVpmg6yKjzZJPwH1vKWIYp39SAP1edXdV7bYhOu9lOxba5N22bnfkt96ynQUsLlhNoM6JBF5+ghrWKYHpUF9lOaMxcjE4r8ElyjPheUv+cN6WXSvF2KQeZbvv+PvwHos2Xz4XRhR1BvF380FVqUHlZ41fsL2oL0RbGpylHV3BxjPMNm/W5WXtIeXpkPLC4m8hOYRgqyis5EHZWHc5tmyotcdyI2I+vgKBL4ms0LcXkC0TeWR049gkdK21IQ4kwWkiOtUr1B0A5eTlcIbD7qiyWYhlI32rdY=
